// Copyright (c) 2015 Zhang Yungui (https://github.com/rhcad/geomedit/), GPL licensed.

'use strict';

angular.module('geomeditApp')
  .service('properties', function() {
    this.properties = [
      { title: 'Start' },
      { title: 'End' },
      { title: 'Line Color' },
      { title: 'Line Width' },
      { title: 'Fill Color' },
      { title: 'Line ColorLine ColorLine ColorLine ColorLine Color' },
      { title: 'Line Color' },
      { title: 'Start' },
      { title: 'End' },
      { title: 'Line Color' },
      { title: 'Line Width' },
      { title: 'Fill Color' },
      { title: 'Line ColorLine ColorLine ColorLine ColorLine Color' },
      { title: 'Start' },
      { title: 'End' },
      { title: 'Line Color' },
      { title: 'Line Width' },
      { title: 'Fill Color' },
      { title: 'Line ColorLine ColorLine ColorLine ColorLine Color' },
      { title: 'Start' },
      { title: 'End' },
      { title: 'Line Color' },
      { title: 'Line Width' },
      { title: 'Fill Color' },
      { title: 'Line ColorLine ColorLine ColorLine ColorLine Color' },
      { title: 'Start' },
      { title: 'End' },
      { title: 'Line Color' },
      { title: 'Line Width' },
      { title: 'Fill Color' },
      { title: 'Line ColorLine ColorLine ColorLine ColorLine Color' },
      { title: 'Start' },
      { title: 'End' },
      { title: 'Line Color' },
      { title: 'Line Width' },
      { title: 'Fill Color' },
      { title: 'Line ColorLine ColorLine ColorLine ColorLine Color' },
      { title: 'Start' },
      { title: 'End' },
      { title: 'Line Color' },
      { title: 'Line Width' },
      { title: 'Fill Color' },
      { title: 'Line ColorLine ColorLine ColorLine ColorLine Color' },
      { title: 'Start' },
      { title: 'End' },
      { title: 'Line Color' },
      { title: 'Line Width' },
      { title: 'Fill Color' },
      { title: 'Line ColorLine ColorLine ColorLine ColorLine Color' },
      { title: 'Start' },
      { title: 'End' },
      { title: 'Line Color' },
      { title: 'Line Width' },
      { title: 'Fill Color' },
      { title: 'Line ColorLine ColorLine ColorLine ColorLine Color' },
      { title: 'Start' },
      { title: 'End' },
      { title: 'Line Color' },
      { title: 'Line Width' },
      { title: 'Fill Color' },
      { title: 'Line ColorLine ColorLine ColorLine ColorLine Color' },
    ];
  });
