'use strict';

angular.module('geomeditApp')
  .config(['$translateProvider', function($translateProvider) {
    var lang = navigator ? (navigator.language || navigator.userLanguage) : null;

    $translateProvider
      .translations('en', {
        Languages:   'UI Language',
        SnapOptions: 'Snapping Options',
        SnapVertex:  'Snap to vertex',
        SnapMid:     'Snap to midpoint',
        SnapCross:   'Snap to intersection',
        SnapGlider:  'Snap to edge',
        ProjectMode: 'Large screen projection',

        ProjectName: 'Geometry Online',
        ProjectDesc: 'Dynamic Mathematics with JSXGraph',
        Blog:        'Blog',
        StartSketch: 'Start for sketch',

        Loading:       'Loading...',
        Cmd_:          'Select',
        CmdPoint:      'Point',
        CmdSegment:    'Segment',
        CmdRay:        'Half-line',
        CmdLine:       'Infinite line',
        CmdTriangle:   'Triangle',
        CmdQuadrangle: 'Quadrangle',
        CmdCircle2p:   'Circle with center',
        CmdCircle3p:   'Circle through 3 points',

        SelectShape:       'Please select a shape.',
        SelectOption:      'Select',
        FaceCircle:        'Circle',
        FaceCross:         'Cross',
        FacePlus:          'Plus',
        FaceDiamond:       'Diamond',
        FaceSquare:        'Square',
        FaceUpTriangle:    'Up Triangle',
        FaceDownTriangle:  'Down Triangle',
        FaceLeftTriangle:  'Left Triangle',
        FaceRightTriangle: 'Right Triangle',

        PropLabel:         'Label',
        PropText:          'Text',
        PropFontSize:      'Text Size',
        PropTextColor:     'Text Color',
        PropFixed:         'Fixed',
        PropTrace:         'Trace',
        PropRange:         'Range',
        PropSnapWidth:     'Snap Width',
        PropFace:          'Face',
        PropSize:          'Size',
        PropStrokeWidth:   'Stroke Width',
        PropStrokeColor:   'Stroke Color',
        PropStrokeOpacity: 'Stroke Opacity',
        PropFillColor:     'Fill Color',
        PropFillOpacity:   'Fill Opacity',
        PropColor:         'Color',
        PropOpacity:       'Opacity',
        PropCoords:        'Coords',
        PropLineEndings:   'Line Endings',
        PropRadius:        'Radius',
        PropCenterVisible: 'Show Center',
        PropDraggable:     'Draggable',
        PropFunctionTerm:  'Function Term'
      })
      .translations('cn', {
        Languages:   '界面语言',
        SnapOptions: '捕捉选项',
        SnapVertex:  '允许捕捉顶点',
        SnapMid:     '允许捕捉中点',
        SnapCross:   '允许捕捉交点',
        SnapGlider:  '允许捕捉线上点',
        ProjectMode: '大屏投影模式',

        ProjectName: '几何绘图',
        ProjectDesc: '基于 JSXGraph 的在线动态几何编辑平台',
        Blog:        '博客',
        StartSketch: '开始绘图',

        Loading:       '正在加载...',
        Cmd_:          '选择',
        CmdPoint:      '点',
        CmdSegment:    '线段',
        CmdRay:        '射线',
        CmdLine:       '直线',
        CmdTriangle:   '三角形',
        CmdQuadrangle: '四边形',
        CmdCircle2p:   '圆心圆',
        CmdCircle3p:   '三点圆',

        SelectShape:       '请选择一个图形',
        SelectOption:      '选择',
        FaceCircle:        '圆点',
        FaceCross:         '叉号',
        FacePlus:          '加号',
        FaceDiamond:       '菱形',
        FaceSquare:        '方形',
        FaceUpTriangle:    '上三角形',
        FaceDownTriangle:  '下三角形',
        FaceLeftTriangle:  '左三角形',
        FaceRightTriangle: '右三角形',

        PropLabel:         '标签',
        PropText:          '文字',
        PropFontSize:      '文字大小',
        PropTextColor:     '文字颜色',
        PropFixed:         '固定',
        PropTrace:         '跟踪位置',
        PropRange:         '变化范围',
        PropSnapWidth:     '捕捉宽度',
        PropFace:          '外观',
        PropSize:          '大小',
        PropStrokeWidth:   '线宽',
        PropStrokeColor:   '线条颜色',
        PropStrokeOpacity: '线条不透明度',
        PropFillColor:     '填充颜色',
        PropFillOpacity:   '填充不透明度',
        PropColor:         '颜色',
        PropOpacity:       '不透明度',
        PropCoords:        '坐标',
        PropLineEndings:   '线端类型',
        PropRadius:        '半径',
        PropCenterVisible: '显示圆心',
        PropDraggable:     '允许拖动',
        PropFunctionTerm:  '函数式'
      })
      .preferredLanguage(lang && lang.toLowerCase().indexOf('cn') >= 0 ? 'cn' : 'en')
      .useSanitizeValueStrategy(null);
  }]);
